# Generated by Django 2.2.5 on 2019-10-01 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20191001_0758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='history',
        ),
        migrations.AddField(
            model_name='history',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Patient'),
        ),
    ]
