# Generated by Django 2.2.5 on 2019-10-01 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20191001_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='hospital_no',
            field=models.IntegerField(null=True),
        ),
    ]
