# Generated by Django 2.2.5 on 2019-10-07 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
