# Generated by Django 2.2.5 on 2019-10-17 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_patient_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(upload_to='articles/')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
