# Generated by Django 2.2.5 on 2019-10-17 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_homepic'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='pic',
            field=models.ImageField(null=True, upload_to='articles/'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='hospital_no',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='name',
            field=models.CharField(max_length=140, unique=True),
        ),
    ]
