# Generated by Django 2.2.5 on 2019-11-25 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_about_help'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='disease',
            field=models.TextField(blank=True, null=True),
        ),
    ]
