# Generated by Django 2.2.5 on 2020-04-25 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='sent_message',
            field=models.BooleanField(default=False),
        ),
    ]
