# Generated by Django 2.2.5 on 2020-05-02 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_patient_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='sent_message_day',
            field=models.BooleanField(default=False),
        ),
    ]
